config/routes.rb
Rails.application.routes.draw do

  root "videos#index"

  get "/videos" => "videos#index"

  get "/videos/new" => "videos#new"

  post "/videos" => "videos#create"

  get "/videos/:id" => "videos#show", as: :video

  get "/videos/:id/edit" => "videos#edit", as: :edit_video

  patch "/videos/:id" => "videos#update"

  delete "/videos/:id" => "videos#destroy", as: :del_video

end

app/models/video.rb
class Video < ActiveRecord::Base

  validates :embed_url, uniqueness: true, presence: true
  validates :title, presence: true

  def youtube_link
    "https://youtu.be/#{self.embed_url}"
  end

  def embed
    '<iframe width="560" height="315" src="https://www.youtube.com/embed/' +
    self.embed_url +
    '" frameborder="0" allowfullscreen></iframe>'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(self.video_params)

    if @video.save
      redirect_to videos_path
    else
      render :new
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
  @video = Video.find(params[:id])

  if @video.update_attributes(params.require(:video).permit(:title, :featured_artist, :released_on, :embed_url))
    redirect_to videos_path
  else
    render :edit
  end
end

  def video_params
    params.require(:video).permit(:title, :embed_url, :released_on, :featured_artists)
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to videos_path
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MrworldwideTvApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1><%= link_to "Mr. Worldwide TV", videos_path %></h1>
    <h3>Dale!</h3>
  </header>

  <nav>
    <%= link_to "Add Video", videos_new_path %>
  </nav>

<%= yield %>

</body>
</html>

app/views/videos/edit.html.erb
<h1>Edit Mr. World Wide's Videos</h1>

<%= form_for @video do |f| %>

    <div>
        <%= f.label :embed_url %>
        <%= f.text_field :embed_url %>
    </div>

    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>

    <div>
        <%= f.label :album %>
        <%= f.text_field :album %>
    </div>

    <div>
        <%= f.label :featured_artists %>
        <%= f.text_field :featured_artists %>
    </div>

    <div>
        <%= f.label :released_on %>
        <%= f.text_field :released_on %>
    </div>

    <div>
        <%= f.label :tags %>
        <%= f.text_field :tags %>
    </div>

    <%= f.submit "Submit your changes" %>

<% end %>

<%= link_to "Back to the list!", videos_path %>

app/views/videos/index.html.erb
<main>
  <% @videos.each do |video| %>
    <article>

      <h4><%= link_to video.title, video.youtube_link %></h4>
      <%= raw video.embed %>
    </article>
  <% end %>
</main>

app/views/videos/new.html.erb
<%= form_for @video do |f| %>

   <%= f.label :title %>
   <%= f.text_field :title %>
  <br>
   <%= f.label :released_on %>
   <%= f.date_select :released_on, order: [:month, :day, :year] %>
  <br>
   <%= f.label :embed_url, "YouTube_Id" %>
   <%= f.text_field :embed_url %>
  <br>
  <%= f.submit "Create!" %>

<% end %>

<ul>
  <% @video.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

app/views/videos/show.html.erb
<h4><%= @video.title %></h4>
<h4><%= @video.released_on %></h4>
<h4><%= @video.embed_url %></h4>

<%= link_to "Edit", edit_video_path %>
<%= link_to "Delete", del_video_path, method: :delete, data: { confirm: "Are you sure?"} %>
<%= link_to "Back to Videos", videos_path %>